core_contact:
        resource: "@CoreBundle/Resources/config/routing/contact.yml"
        prefix:   /contact

core_tache:
        resource: "@CoreBundle/Resources/config/routing/tache.yml"
        prefix:   /tache


core_homepage:
    path:     /
    defaults: { _controller: CoreBundle:Default:index }
